name: confereshop
description: App oficial Confere Shop (Desafio Software Engineer, Mobile Developer)
version: 1.0.1+101

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.16.0
  pull_to_refresh: ^1.6.4
  flare_flutter: ^2.0.6
  font_awesome_flutter: ^8.5.0
  line_awesome_icons: ^1.0.4+2
  date_format: ^1.0.9
  mask_text_input_formatter: ^1.1.0
  shared_preferences: any
  path: ^1.6.4
  path_provider: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_staggered_animations: ^0.1.3
  shimmer: ^1.1.2
  sqflite: any
  connectivity: ^0.4.4
  flutter_masked_text: ^0.8.0
  badges: ^1.1.0
  bottom_navy_bar: ^6.0.0
  animated_text_kit: ^4.2.1
  cached_network_image: ^2.3.3
  flutter_slidable: ^0.6.0
  # bloc_pattern: ^3.0.0
  # rxdart: ^0.27.1
  rxdart: ^0.24.1
  bloc_pattern: ^2.1.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  mobx_codegen: ^1.1.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/flare/
